{{- if .Values.image.fromGcHub }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operational-transformation.name" . }}-docker-config
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "operational-transformation.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ include "operational-transformation.docker-config" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}