apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operational-transformation.name" . }}-secret
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "operational-transformation.labels" . | nindent 4 }}
type: Opaque
data:
  EXAMPLE: eHh4eA==