apiVersion: v1
kind: Service
metadata:
  name: {{ include "operational-transformation.name" . }}-service
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "operational-transformation.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "operational-transformation.coreSelectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }} # to access pods internally
      targetPort: 9000 # application port
    