#kubectl create namespace operational-transformation
#kubectl config set-context --current --namespace=operational-transformation

#helm install operational-transformation ./helm --namespace=operational-transformation --set ingress.hosts\[0\]=template.xxx.dev
#helm install --dry-run operational-transformation ./helm --namespace=operational-transformation --set ingress.hosts\[0\]=operational-transformation.xxx.dev
#helm upgrade --dry-run operational-transformation ./helm --namespace=operational-transformation --set ingress.hosts\[0\]=operational-transformation.xxx.dev
#helm upgrade operational-transformation ./helm --namespace=operational-transformation --set ingress.hosts\[0\]=operational-transformation.xxx.dev
#helm uninstall operational-transformation --namespace=operational-transformation 

apiVersion: v1
name: operational-transformation
description: A helm chart for operational-transformation kubernetes deployment
type: application

dependencies:

sources:
  - https://github.com/adhityan/node-microsite-template

maintainers:
  - name: K V Adhityan
    email: adhityan@hotmail.com

version: 1.0.0